import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  const formData = await req.formData();
  const targetLang = formData.get("targetLang") || "en";
  const image = formData.get("image");

  if (!image) {
    return NextResponse.json(
      { error: "No image provided" },
      { status: 400 }
    );
  }

  // Dummy implementation for now
  const originalText =
    "This is dummy original text. In the real version, this will be the text extracted from your magazine page.";
  const translatedText =
    `This is dummy translated text in language: ${targetLang}. Later this will be generated by the AI model.`;

  return NextResponse.json(
    { originalText, translatedText },
    { status: 200 }
  );
}
